### ISSUE TITLE
Problem with training

### ISSUE THREAD

**Issue by ZFTurbo** [starrytong/SCNet#1]
I added your model in my training pipeline. But learning process is very slow and for the more of that day of training model reach only:
Instr SDR vocals: 5.8361. It's too small comparing to other even weak models.

May be there are some normalization on other tricks we need to do on inference step?

**Comment by starrytong** [comment]
I tried your training pipeline, and by the second epoch, the SDR for vocals had already reached 6.1, so could there be some configuration error?
![image](https://github.com/starrytong/SCNet/assets/16458309/0d54dde2-9ea6-45af-b985-f30cb93bffb3)

**Comment by ZFTurbo** [comment]
Could you post your config may be? What did you use for training and for validation?

**Comment by lucellent** [comment]
> Could you post your config may be? What did you use for training and for validation?

Looks like MUSDB validation (50 songs)

**Comment by starrytong** [comment]
Using 4 GPUs, train and test on musdb18
```
audio:
  chunk_size: 441000
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.001

model:
  sources: ['drums', 'bass', 'other', 'vocals']
  audio_channels: 2
  dims: [4, 32, 64, 128], #[4, 64, 128, 256] in SCNet-large
  nfft: 4096
  hop_size: 1024
  win_size: 4096
  normalized: True
  band_configs: {
    'low': { 'SR': .175, 'stride': 1, 'kernel': 3 },
    'mid': { 'SR': .392, 'stride': 4, 'kernel': 4 },
    'high': {'SR': .433, 'stride': 16, 'kernel': 16 }
  }
  #SR=[.225, .372, .403] in SCNet-large                      
  conv_depths: [3,2,1] 
  compress: 4
  conv_kernel: 3
  num_dplayer: 6
  expand: 1


training:
  batch_size: 8
```

**Comment by ZFTurbo** [comment]
Earlier I trained only ['vocals', 'other'] model with my vocals dataset. Now I switched on MUSDB18 dataset with 4 stems.  And it's also not great - SDR for vocals less than 2 after 2 epochs. What's the settings for training did you use in config? I train with less batch size on 3 x 48 GB cards. But I don't think it can have such big impact.

**Comment by ZFTurbo** [comment]
My current config:
```
audio:
  chunk_size: 441000
  num_channels: 2
  sample_rate: 44100
  min_mean_abs: 0.000

model:
  sources: ['drums', 'bass', 'other', 'vocals']
  audio_channels: 2
  dims: [4, 32, 64, 128] #[4, 64, 128, 256] in SCNet-large
  nfft: 4096
  hop_size: 1024
  win_size: 4096
  normalized: True
  band_configs: {
    'low': { 'SR': .175, 'stride': 1, 'kernel': 3 },
    'mid': { 'SR': .392, 'stride': 4, 'kernel': 4 },
    'high': { 'SR': .433, 'stride': 16, 'kernel': 16 }
  }
  # SR=[.225, .372, .403] in SCNet-large
  conv_depths: [3, 2, 1]
  compress: 4
  conv_kernel: 3
  # Dual-path RNN
  num_dplayer: 6
  expand: 1
  # mamba
  use_mamba: False
  mamba_config: {
    'd_stat': 16,
    'd_conv': 4,
    'd_expand': 2
  }

training:
  batch_size: 4
  gradient_accumulation_steps: 1
  grad_clip: 0
  instruments:
    - drums
    - bass
    - other
    - vocals
  lr: 4.0e-05
  patience: 2
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: adam
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true
```

**Comment by starrytong** [comment]
This is my config, with different lr and batch_size. I fully adopted your configuration (3 GPUs, batch=4, lr=4.0e-5), and after the second epoch, the SDR for the vocal was 2.6303. Additionally, with batch_size of 4, it only used about 10GB of GPU memory, may be could try a larger batch size?
‘’‘
  batch_size: 8
  gradient_accumulation_steps: 1
  grad_clip: 0
  instruments:
    - drums
    - bass
    - other
    - vocals
  lr: 5.0e-04
  patience: 2
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: adam
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true
‘’‘

**Comment by starrytong** [comment]
This is my config, with different lr and batch_size. I fully adopted your configuration (3 GPUs, batch=4, lr=4.0e-5), and after the second epoch, the SDR for the vocal was 2.6303. Additionally, with batch_size of 4, it only used about 10GB of GPU memory, may be could try a larger batch size?
```
  batch_size: 8
  gradient_accumulation_steps: 1
  grad_clip: 0
  instruments:
    - drums
    - bass
    - other
    - vocals
  lr: 5.0e-04
  patience: 2
  reduce_factor: 0.95
  target_instrument: null
  num_epochs: 1000
  num_steps: 1000
  q: 0.95
  coarse_loss_clip: true
  ema_momentum: 0.999
  optimizer: adam
  other_fix: false # it's needed for checking on multisong dataset if other is actually instrumental
  use_amp: true # enable or disable usage of mixed precision (float16) - usually it must be true
```
